# Generated by Django 6.0.6 on 2026-06-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store89', '0003_alter_customermodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
