# Generated by Django 6.0.6 on 2026-06-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store89', '0004_alter_customermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodoel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
